[accounts.deployer]
mnemonic = "point approve language letter cargo rough similar wrap focus edge polar task olympic tobacco blanket update humor much ocean mom area ghost piece actress"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "hurry aunt blame peanut heavy update captain human rice crime juice adult scale device promote vast project quiz unit note reform update climb purchase"
balance = 100000000000000
