[accounts.deployer]
mnemonic = "female autumn drive capable scorpion congress hockey chunk mouse cherry blame trumpet monk inject mother mask library cargo assist pig toward radar venture deal"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "hurry aunt blame peanut heavy update captain human rice crime juice adult scale device promote vast project quiz unit note reform update climb purchase"
balance = 100000000000000
