[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "coyote spin barely worth box clip addict spoil sock spirit style exotic"
balance = 100000000000000
